name: Compile and Release

on: 
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      archive: pogify-streamer-client-win10
      url: https://pogify-br-edgehtml-compat.herokuapp.com/
    steps:
    - uses: actions/checkout@v2
    - name: Print GitHub context
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }} 
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - name: Download the package
      run: |
        node index.js --url=$url --archive $archive
    - name: Zip the app
      run: |
        cd ./$archive/projects/windows10
        zip -r ../../../$archive.zip *
        cd ../../..
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.archive }}.zip
        asset_name: ${{ env.archive }}.zip
        tag: ${{ github.ref }}
        overwrite: true